### ISSUE TITLE
Create Rally Account

### ISSUE THREAD

**Issue by jepstein** [mozilla-rally/rally-web-platform#116] opened 2021-09-07 13:05 UTC
As a user, I want to create a Rally account, so that I may become a Rally user and participant.

DOD:
A create account form that follows UX styling and design.
A user may use a Google account or email & password to create their account.
In order to create their account, a user must consent.

**Comment by marniepw** [comment] 2021-09-07 15:32
Task of #117

**Comment by Carla-Moz** [comment] 2021-09-22 13:52
Duplicate of #139

**Closed by Carla-Moz** 2021-09-22 13:52 UTC
Labels: web-platform
